version: '2'
services:
    web:
        build: .
        depends_on:
            - mongo
        env_file: .env
        environment:
            - PORT=3000
            - DATABASE_URL=mongodb://mongo/db
            - DEBUG=*,-mquery
        ports:
            - "$PORT:3000"
    scheduler:
        build: .
        depends_on:
            - mongo
        env_file: .env
        environment:
            - DATABASE_URL=mongodb://mongo/db
            - DEBUG=reminder-scheduler
        command: npm run scheduler

    mongo:
        image: mongo
